# Dockerfile.streamlit
FROM python:3.9-slim

WORKDIR /streamlit

# Installation des dépendances
COPY requirements.streamlit.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copie de l'application Streamlit
COPY streamlit/ .

# Copie du fichier drift_config.py depuis le dossier dags
COPY ./dags/drift_config.py /streamlit/drift_config.py

# Exposition du port Streamlit
EXPOSE 8501

# Commande de démarrage
CMD ["streamlit", "run", "app.py"]
